version: '3.4'

networks:
  apidemo:

services:
  demoappdb:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - apidemo
  demoapiapp:
    container_name: demo-api-app
    image: ${DOCKER_REGISTRY-}demoapiapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:80
    depends_on:
      - demoappdb
    environment:
      - DB_HOST=demoappdb
      - DB_NAME=DemoApiApp
      - DB_SA_PASSWORD=password@12345#
    networks:
      - apidemo
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080 
    networks:
      - apidemo